# Generated by Django 5.2.7 on 2025-11-04 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresasConstructoras',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('rut_empresa', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('certificacion_industrializada', models.IntegerField(blank=True, null=True)),
                ('años_experiencia', models.IntegerField(blank=True, null=True)),
                ('capacidad_construccion_anual', models.IntegerField(blank=True, null=True)),
                ('estado_empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresas_constructoras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instituciones',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_institucion', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_institucion', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email_contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instituciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('codigo_municipio', models.CharField(blank=True, max_length=10, null=True)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'municipios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
                ('codigo_region', models.CharField(blank=True, max_length=10, null=True)),
                ('capital_regional', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'regiones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id_beneficiario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('ingresos_familiares', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_integrantes', models.IntegerField(blank=True, null=True)),
                ('puntaje_socioeconomico', models.IntegerField(blank=True, null=True)),
                ('estado_beneficiario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.municipios')),
            ],
            options={
                'db_table': 'beneficiarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProyectosHabitacionales',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_viviendas', models.IntegerField(blank=True, null=True)),
                ('tipo_vivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('superficie_vivienda', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('estado_proyecto', models.CharField(blank=True, max_length=50, null=True)),
                ('certificacion_ambiental', models.CharField(blank=True, max_length=50, null=True)),
                ('tecnologia_construccion', models.CharField(blank=True, max_length=100, null=True)),
                ('id_empresa_constructora', models.ForeignKey(blank=True, db_column='id_empresa_constructora', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.empresasconstructoras')),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.municipios')),
            ],
            options={
                'db_table': 'proyectos_habitacionales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Postulaciones',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_postulacion', models.DateField(blank=True, null=True)),
                ('estado_postulacion', models.CharField(blank=True, max_length=50, null=True)),
                ('puntaje_asignado', models.IntegerField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('documentos_adjuntos', models.TextField(blank=True, null=True)),
                ('id_beneficiario', models.ForeignKey(blank=True, db_column='id_beneficiario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.beneficiarios')),
                ('id_proyecto', models.ForeignKey(blank=True, db_column='id_proyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.proyectoshabitacionales')),
            ],
            options={
                'db_table': 'postulaciones',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='municipios',
            name='id_region',
            field=models.ForeignKey(blank=True, db_column='id_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.regiones'),
        ),
        migrations.CreateModel(
            name='Terrenos',
            fields=[
                ('id_terreno', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('superficie_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('coordenadas_gps', models.CharField(blank=True, max_length=50, null=True)),
                ('servicios_agua', models.IntegerField(blank=True, null=True)),
                ('servicios_electricidad', models.IntegerField(blank=True, null=True)),
                ('servicios_alcantarillado', models.IntegerField(blank=True, null=True)),
                ('acceso_transporte', models.IntegerField(blank=True, null=True)),
                ('factibilidad_construccion', models.IntegerField(blank=True, null=True)),
                ('estado_terreno', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('id_municipio', models.ForeignKey(blank=True, db_column='id_municipio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.municipios')),
            ],
            options={
                'db_table': 'terrenos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proyectoshabitacionales',
            name='id_terreno',
            field=models.ForeignKey(blank=True, db_column='id_terreno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.terrenos'),
        ),
        migrations.CreateModel(
            name='UsuariosSistema',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('beneficiario', models.OneToOneField(blank=True, db_column='id_beneficiario_rel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appejemplo.beneficiarios')),
                ('id_empresa', models.ForeignKey(blank=True, db_column='id_empresa_rel', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appejemplo.empresasconstructoras')),
                ('id_institucion', models.ForeignKey(blank=True, db_column='id_institucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appejemplo.instituciones')),
            ],
            options={
                'db_table': 'usuarios_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'admin'), ('usuario', 'usuario'), ('empresa', 'empresa')], default='usuario', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuariosistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appejemplo.usuariossistema')),
            ],
        ),
    ]
