# Generated by Django 5.2.7 on 2025-11-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appejemplo', '0002_add_fecha_aprobacion_to_postulaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('tabla', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_afectado', models.IntegerField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appejemplo.usuariossistema')),
            ],
            options={
                'db_table': 'log_auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id_matching', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_compatibilidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_matching', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('id_beneficiario', models.ForeignKey(db_column='id_beneficiario', on_delete=django.db.models.deletion.CASCADE, to='appejemplo.beneficiarios')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='appejemplo.proyectoshabitacionales')),
            ],
            options={
                'db_table': 'matching',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('canal', models.CharField(blank=True, max_length=20, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='appejemplo.usuariossistema')),
            ],
            options={
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
    ]
