# Generated by Django 5.2.7 on 2025-12-02 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appejemplo', '0007_alter_evento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresasconstructoras',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='empresasconstructoras',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='proyectoshabitacionales',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='proyectoshabitacionales',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='terrenos',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='terrenos',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
    ]
